In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data=pd.read_csv("TeluguMovies_dataset.csv")

In [3]:
movies_data.head()

index                        Movie    Year Certificate  \
0      0      Bahubali: The Beginning  2015.0          UA   
1      1  Baahubali 2: The Conclusion  2017.0          UA   
2      2              1 - Nenokkadine  2014.0          UA   
3      3                      Dhoom:3  2013.0          UA   
4      4                       Ra.One  2011.0           U   

                                   Genre  \
0              Action, Drama               
1              Action, Drama               
2           Action, Thriller               
3           Action, Thriller               
4  Action, Adventure, Sci-Fi               

                                            Overview  Runtime  Rating  \
0      In ancient India, an adventurous and darin...      159     8.1   
1      When Shiva, the son of Bahubali, learns ab...      167     8.2   
2      A rock star must overcome his psychologica...      170     8.1   
3      When Sahir, a circus entertainer trained i...      172     5.4   
4      When the titular antagonist of an action g...      156     4.6   

   No.of.Ratings  
0          99114  
1          71458  
2          42372  
3          42112  
4          37211

In [4]:
movies_data.shape

(1400, 9)

In [5]:
movies_data.isnull().sum()

index              0
Movie              0
Year              48
Certificate      449
Genre             11
Overview         179
Runtime            0
Rating             0
No.of.Ratings      0
dtype: int64

In [6]:
selected_features=['Genre','Movie','Overview']

In [7]:
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [10]:
movies_data[['Genre','Movie','Overview']].isnull().sum()

Genre       0
Movie       0
Overview    0
dtype: int64

In [12]:
combined_features = movies_data['Genre']+' '+movies_data['Movie']+' '+movies_data['Overview']

In [13]:
print(combined_features)

0       Action, Drama             Bahubali: The Beginn...
1       Action, Drama             Baahubali 2: The Con...
2       Action, Thriller             1 - Nenokkadine  ...
3       Action, Thriller             Dhoom:3     When ...
4       Action, Adventure, Sci-Fi             Ra.One  ...
                              ...                        
1395                                       Maro Monagadu 
1396    Comedy, Drama             Jakkanna     The mov...
1397    Drama, Romance             Muvva Gopaludu     ...
1398     Ninney Ishta Paddaanu     Hero Charan (Tarun)...
1399    Drama             9 Nelalu     Surendra marrie...
Length: 1400, dtype: object


In [14]:
vectorizer = TfidfVectorizer()

In [15]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [16]:
print(feature_vectors)

  (0, 4319)	0.1928732604944429
  (0, 6534)	0.2837866798340414
  (0, 6169)	0.15781505730416462
  (0, 740)	0.17609654145477932
  (0, 2067)	0.2606317482342353
  (0, 4095)	0.21325020405606415
  (0, 1485)	0.2745537850890944
  (0, 2799)	0.23195175760409958
  (0, 696)	0.1977467079436342
  (0, 3479)	0.12913506667402888
  (0, 1447)	0.3124666704641771
  (0, 353)	0.07208409715812306
  (0, 214)	0.2837866798340414
  (0, 339)	0.1064045129508743
  (0, 2703)	0.1818411048739418
  (0, 352)	0.2745537850890944
  (0, 2690)	0.15834279963742298
  (0, 704)	0.3124666704641771
  (0, 5961)	0.06646609204545577
  (0, 628)	0.29568995142451354
  (0, 1734)	0.06926665194621266
  (0, 159)	0.07411837375549563
  (1, 3106)	0.21598240725563547
  (1, 3447)	0.264545409940482
  (1, 6221)	0.25034164219395394
  :	:
  (1399, 5796)	0.42432975321274025
  (1399, 3546)	0.1686313068467555
  (1399, 3933)	0.19699915284442912
  (1399, 2619)	0.15439342894764932
  (1399, 4140)	0.16246677417293193
  (1399, 3720)	0.14283074533719903
  (1399

In [17]:
similarity=cosine_similarity(feature_vectors)

In [18]:
print(similarity)

[[1.         0.10457084 0.00618659 ... 0.02674187 0.01652326 0.04053726]
 [0.10457084 1.         0.04961868 ... 0.03508289 0.07909854 0.05722518]
 [0.00618659 0.04961868 1.         ... 0.         0.03889234 0.01153394]
 ...
 [0.02674187 0.03508289 0.         ... 1.         0.04434499 0.01276055]
 [0.01652326 0.07909854 0.03889234 ... 0.04434499 1.         0.02776065]
 [0.04053726 0.05722518 0.01153394 ... 0.01276055 0.02776065 1.        ]]


In [19]:
movie_name=input('enter the movie name:')

enter the movie name:evadu


In [20]:
list_of_all_titles=movies_data['Movie'].tolist()
print(list_of_all_titles)

['Bahubali: The Beginning', 'Baahubali 2: The Conclusion', '1 - Nenokkadine', 'Dhoom:3', 'Ra.One', 'Dhoom:2', 'Eega', 'Krrish 3', 'Arjun Reddy', 'Rangasthalam', 'Magadheera', 'War', 'Bharat Ane Nenu', 'Saaho', 'Theri', 'Dookudu', 'Pokiri', 'Sarkar', 'Athadu', 'The Ghazi Attack', 'Kabali', 'MSG: The Messenger of God', 'Nanban', 'Srimanthudu', 'Veer - Vivegam', 'Billa 2', 'Manam', '7 Aum Arivu', 'Bigil', 'Business Man', 'Geetha Govindam', 'Mahanati', 'Spyder', 'Nannaku Prematho', 'Dabangg 3', 'MSG 2 the Messenger', 'Manikarnika: The Queen of Jhansi', 'Race Gurram', 'Okkadu', 'Bommarillu', 'Atharintiki Daaredi', 'Khaleja', 'Yennai Arindhaal', 'Thalaivaa', 'Kaala', 'Bairavaa', 'Goodachari', 'Puli', 'Pulimurugan', 'Veeram', 'Vedam', 'Yevadu', 'Aravindha Sametha Veera Raghava', 'Billa', 'Jersey', 'Sye Raa Narasimha Reddy', 'Ala Vaikunthapurramuloo', 'Janatha Garage', 'Gabbar Singh', 'Temper', 'Game Over', 'Singam 2', 'Dhruva', 'Jalsa', 'Maharshi', 'Pelli Choopulu', 'Arya 2', 'Chekka Chivanth

In [21]:
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Yevadu', 'Devadasu', 'Devadasu']


In [22]:
close_match=find_close_match[0]
print(close_match)

Yevadu


In [23]:
index_of_the_movie = movies_data[movies_data.Movie == close_match]['index'].values[0]
print(index_of_the_movie)

51


In [24]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.03462618771941496), (1, 0.06409685539366722), (2, 0.10091084151233282), (3, 0.04558922861904379), (4, 0.01812470189482289), (5, 0.045132844694829345), (6, 0.12927758187710525), (7, 0.04874892940393154), (8, 0.06865950879318719), (9, 0.03362151379406405), (10, 0.04402928806688789), (11, 0.05561793042682699), (12, 0.044778550583374356), (13, 0.030292189416371088), (14, 0.045951989628117806), (15, 0.03809746888960599), (16, 0.07761045651516246), (17, 0.022134776548574233), (18, 0.07325064042096209), (19, 0.1028357859527238), (20, 0.06388413865863055), (21, 0.013768734400719594), (22, 0.05436147761805448), (23, 0.06741619375303393), (24, 0.1410137836050662), (25, 0.019224757904142836), (26, 0.015071429895061722), (27, 0.073337217921345), (28, 0.025625674643135286), (29, 0.12542786294806346), (30, 0.06310035556492666), (31, 0.014520104990165138), (32, 0.024812953306276125), (33, 0.08895028195417302), (34, 0.03521941190907138), (35, 0.025538965416394267), (36, 0.011297728363008915), (

In [25]:
len(similarity_score)

1400

In [28]:
sorted_similar_movies=sorted(similarity_score, key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(51, 1.0000000000000002), (1153, 0.18142802602191135), (238, 0.16245636130583935), (561, 0.15996628829213658), (784, 0.1580204733031559), (271, 0.15301594926974002), (410, 0.14827449979148774), (826, 0.1432900615669084), (24, 0.1410137836050662), (923, 0.1407773712123949), (795, 0.1399509354170897), (558, 0.13959202562144113), (1198, 0.13541917351811586), (140, 0.1347784568942121), (1051, 0.13436794889227904), (1018, 0.13384366455160512), (873, 0.13182378536268446), (837, 0.1302901846552796), (6, 0.12927758187710525), (679, 0.1292257883591863), (1076, 0.12860939281219846), (29, 0.12542786294806346), (1094, 0.12485744163222837), (818, 0.11999716047692423), (493, 0.11886727360350566), (249, 0.11855063138330203), (94, 0.11798591701108366), (161, 0.11734492689362705), (574, 0.11668344704147865), (418, 0.1160621298462892), (185, 0.11487259039652102), (552, 0.11485955979229481), (322, 0.11481306163285922), (595, 0.11291086775184228), (146, 0.10989086458736116), (983, 0.10983068717111585), (

In [29]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['Movie'].values[0]
  if (i<10):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Yevadu
2 . Om 3D
3 . Rebel
4 . Yuddham Sharanam
5 . Vijayendra Varama
6 . Suryam
7 . Swathi Muthyam
8 . Padmavyuham
9 . Veer - Vivegam


In [30]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['Movie'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.Movie == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['Movie'].values[0]
  if (i<10):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : yevadu
Movies suggested for you : 

1 . Yevadu
2 . Om 3D
3 . Rebel
4 . Yuddham Sharanam
5 . Vijayendra Varama
6 . Suryam
7 . Swathi Muthyam
8 . Padmavyuham
9 . Veer - Vivegam
